services:
  cumplo-herald:
    image: cumplo-herald
    env_file: .env
    ports:
      - 8002:8080
    build:
      context: .
      dockerfile: Dockerfile.development
      args: 
        - CUMPLO_PYPI_BASE64_KEY
    volumes:
      - ./cumplo_herald:/app/cumplo_herald
      - /app/.venv
