[tool.poetry]
name = "cumplo-scraper"
version = "0.1.0"
description = "Cumplo scraper"
authors = ["Cristobal Sfeir <cnsfeir@uc.cl>"]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.28.1"
arrow = "^1.2.3"
pydantic = "^2.1.1"
python-dotenv = "^1.0.0"
aiohttp = "^3.8.3"
asyncio = "^3.4.3"
google-cloud-logging = "^3.5.0"
starlette = "<0.28.0"
fastapi = "^0.101.0"
uvicorn = "^0.23.1"
case-converter = "^1.1.0"
cumplo-common = "^0.2.2"

[tool.poetry.dev-dependencies]
pylint = "^2.17.2"
flake8 = "^6.0.0"
black = "^23.3.0"
mypy = "^1.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
